export const ADD_TODO: string = 'ADD_TODO'
export const DELETE_TODO: string = 'DELETE_TODO'
export const EDIT_TODO: string = 'EDIT_TODO'
export const COMPLETE_TODO: string = 'COMPLETE_TODO'
export const COMPLETE_ALL_TODOS: string = 'COMPLETE_ALL_TODOS'
export const CLEAR_COMPLETED: string = 'CLEAR_COMPLETED'
export const SET_VISIBILITY_FILTER: string = 'SET_VISIBILITY_FILTER'
